title: Simple Example Game
subtitle: A game used for demo purposes
introduction: |
  # The Simple Example
  
  ## Who

  You are a person playing a game...
  
  ## What

  The game revolves around you playing games...

labels:
  failureCheckLoss: 'You have lost the game'
  successCheckWin: 'You have won the game!'
