title: Example Game
subtitle: A game used for demo purposes
introduction: This is an example game... #default value: intro.md to attempt read from a markdown file
stylesheet: 'game.css' #default value
deck: 'deck.csv' #default value
availableDiceThemes:
  - name: default
    foreground: white
    background: '#1387b9'
    texture: glass
    description: Default dice
availableDiceTables:
  - name: default
    url: '/assets/table1-bg.png'
  - name: dark mode
    url: '/assets/table1-dark-bg.png'
labels:
  introNextButtonText: 'Next'
  introBackButtonText: 'Back'
  introStartButtonText: 'Start'
  introExitButtonText: 'Exit'
  toolbarExitButtonText: 'Exit'
  journalEntryHeader: 'Record your journal entry'
  journalEntrySubHeader: 'Summary of events'
  journalEntryNextButtonText: 'Continue'
  journalEntrySaveButtonText: 'Record'
  journalEntryRestartButtonText: 'Restart'
  journalEntryExitButtonText: 'New Game'
  rollForTasksHeader: 'Roll for tasks'
  rollForTasksResultHeader: 'Click to continue'
  drawCardButtonText: 'Draw Card'
  successCheckHeader: 'Roll success check'
  successCheckResultHeader: 'Click to continue'
  failureCheckHeader: 'Failure Check'
  failureCheckLoss: 'You have lost the game'
  successCheckWin: 'You have won the game!'
  gameOverHeader: 'Game Over'
  gameOverButtonText: 'Record your final log'
  statusDisplayRoundText: 'Round: '
  healthMeterHeader: 'Health Meter'
  healthMeterSvg: null
  failureCounterHeader: 'Failure Counters'
  failureCounterSvg: null