title: "The Artful Detective"
subtitle: "A Comedy of Errors and Art"
introduction: |
  # The Artful Detective
  
  ## Who

  You are a private eye, known for your unconventional methods and slapstick humor. You've been hired to track down a stolen artifact from a group of international art thieves. You're not the most graceful, and your investigations often lead to hilarious mishaps. But you have a knack for stumbling upon clues and piecing together the puzzle in the most unexpected ways.

  ## What

  The game revolves around your investigation into the theft. You'll encounter various characters, stumble upon clues, and face numerous challenges. The goal is to recover the stolen artifact before it's too late. But remember, in this comedy of errors, even your failures can lead to unexpected breakthroughs.
